# Generated by Django 3.0.1 on 2020-01-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('last_pull', models.DateTimeField(blank=True, null=True)),
                ('alphavantage_status', models.IntegerField(default=200)),
                ('yahoo_status', models.IntegerField(default=200)),
                ('sp500_member', models.BooleanField(default=False)),
                ('spdr_member', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('ticker_datetime', models.DateTimeField()),
                ('volume', models.BigIntegerField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('frequency', models.BigIntegerField()),
                ('dividends', models.FloatField(blank=True, null=True)),
                ('stock_splits', models.FloatField(blank=True, null=True)),
                ('market_average', models.FloatField(blank=True, null=True)),
                ('market_notional', models.FloatField(blank=True, null=True)),
                ('market_change_over_time', models.FloatField(blank=True, null=True)),
                ('notional', models.FloatField(blank=True, null=True)),
                ('number_of_trades', models.FloatField(blank=True, null=True)),
                ('change_over_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
