# Generated by Django 3.0.1 on 2020-01-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='adjusted_close',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
