# Generated by Django 3.0.1 on 2020-01-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0002_tick_adjusted_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_number_of_trades',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_open',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tick',
            name='market_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
