# Generated by Django 3.0.1 on 2020-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0003_auto_20200109_0638'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tick',
            constraint=models.UniqueConstraint(fields=('symbol', 'ticker_datetime'), name='one_bar_per_symbol'),
        ),
    ]
