# Generated by Django 3.0.1 on 2020-01-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0004_auto_20200109_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='tick',
            name='source',
            field=models.CharField(default='penis', max_length=30),
            preserve_default=False,
        ),
    ]
