# Generated by Django 3.0.3 on 2020-02-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0006_symbol_iex_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='alphavantage_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='iex_status',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='yahoo_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
