# Generated by Django 3.0.3 on 2020-02-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0007_auto_20200222_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='sp500_member',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='spdr_member',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
