# Generated by Django 3.0.3 on 2020-02-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickerdata', '0008_auto_20200222_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tick',
            name='volume',
            field=models.FloatField(),
        ),
    ]
