# Generated by Django 3.0.3 on 2020-02-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255, unique=True)),
                ('pull_historical', models.BooleanField(default=True)),
                ('pull_live', models.BooleanField(default=True)),
                ('pull_options', models.BooleanField(default=True)),
            ],
        ),
    ]
