# Generated by Django 3.0.3 on 2020-02-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockLists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='members',
            field=models.TextField(blank=True, null=True),
        ),
    ]
