# Generated by Django 3.0.3 on 2020-03-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classSpeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('speed', models.FloatField()),
                ('failed', models.BooleanField(default=False)),
                ('test_field', models.CharField(max_length=255)),
            ],
        ),
    ]
