# Generated by Django 3.0.3 on 2020-03-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_historical_fetches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_fetches',
            name='status',
            field=models.TextField(),
        ),
    ]
